import type { TemplateDefinition } from "../types.js";

export const EMPLOYEE_SCHEDULE: TemplateDefinition = {
  id: "employee-schedule",
  name: "Employee Schedule",
  category: "schedule",
  description:
    "Plan weekly employee shifts with time slots, departments, and coverage across a seven-day schedule.",
  design: {
    palette: {
      titleBg: "#FFFCD3",
      titleFg: "#1E1E1E",
      headerBg: "#FAFB88",
      headerFg: "#1E1E1E",
      labelBg: "#FAFB88",
      labelFg: "#323232",
      accentBg: "#305496",
      accentFg: "#FFFFFF",
      alternateBg: "",
      totalBg: "#CFE8D6",
      totalFg: "#323232",
    },
    typography: {
      fontFamily: "Arial",
      titleFontFamily: "Bodoni 72 Book",
      titleSize: 50,
      sectionHeaderSize: 16,
      headerSize: 14,
      bodySize: 14,
    },
    alternatingRows: false,
    titleBold: false,
    titleRowHeight: 98,
    defaultRowHeight: 36,
    headerRowHeight: 42,
  },
  structure: {
    title: "Employee Work Schedule",
    titleRow: 1,
    metaFields: [
      { label: "Month:", placeholder: "June 2030", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Shift:", placeholder: "9:00 AM - 5:00 PM", row: 2, labelCol: "D", valueCol: "E" },
      { label: "Shift Manager:", placeholder: "Lila Akiyama", row: 3, labelCol: "A", valueCol: "B" },
    ],
    headerRow: 5,
    columns: [
      { header: "Employee Name", col: "A", width: 32, alignment: "Left" },
      { header: "Position", col: "B", width: 18, alignment: "Left" },
      { header: "MON", col: "C", width: 12, alignment: "Center" },
      { header: "TUE", col: "D", width: 13, alignment: "Center" },
      { header: "WED", col: "E", width: 13, alignment: "Center" },
      { header: "THU", col: "F", width: 13, alignment: "Center" },
      { header: "FRI", col: "G", width: 13, alignment: "Center" },
      { header: "SAT", col: "H", width: 13, alignment: "Center" },
      { header: "SUN", col: "I", width: 12, alignment: "Center" },
      { header: "Hours/Week", col: "J", width: 20, alignment: "Center", isAccent: true },
    ],
    sampleData: [
      ["Katrianne Schulz", "Cashier", "9-5", "9-5", "9-5", "9-5", "9-5", null, null, 40],
      ["Arkin Bhatt", "Stock Clerk", "9-5", "9-5", "9-5", "9-5", "9-5", null, null, 40],
      ["Boris Ercken", "Floor Associate", "9-5", "9-5", null, "9-5", "9-5", null, null, 32],
      ["Charina Kimura", "Sales Lead", "9-5", null, "9-5", "9-5", null, "9-5", null, 32],
      ["Kit Bauwens", "Shift Lead", "9-5", "9-5", "9-5", "9-5", "9-5", null, null, 40],
    ],
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "spacer", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: [6, 10] },
    ],
    columnSpan: "A:J",
    totalRows: 11,
  },
  sourceKind: "bundled",
};
