import type { TemplateDefinition } from "../types.js";

export const GOAL_TRACKING: TemplateDefinition = {
  id: "goal-tracking",
  name: "Goal Tracking",
  category: "tracking",
  description:
    "Set and monitor goals across Health, Career, and Finance categories with progress bars, priorities, and next actions.",
  design: {
    palette: {
      titleBg: "#7ED957",
      titleFg: "#244B14",
      headerBg: "#244B14",
      headerFg: "#7ED957",
      labelBg: "#D9EDD1",
      labelFg: "#244B14",
      accentBg: "#0CC0DF",
      accentFg: "#FFFFFF",
      alternateBg: "",
      totalBg: "#244B14",
      totalFg: "#7ED957",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Cambria",
      titleSize: 56,
      sectionHeaderSize: 14,
      headerSize: 14,
      bodySize: 11,
    },
    alternatingRows: false,
    titleBold: false,
    titleRowHeight: 100,
    defaultRowHeight: 30,
    headerRowHeight: 32,
  },
  structure: {
    title: "Goal Tracker",
    titleRow: 1,
    metaFields: [
      { label: "Week of:", placeholder: "Jan 7", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Wins:", placeholder: "7 out of 9", row: 2, labelCol: "F", valueCol: "G" },
    ],
    headerRow: 6,
    columns: [
      { header: "Goal", col: "A", width: 41, alignment: "Left" },
      { header: "Priority", col: "B", width: 18, alignment: "Left" },
      { header: "10%", col: "C", width: 7, alignment: "Center" },
      { header: "20%", col: "D", width: 8, alignment: "Center" },
      { header: "30%", col: "E", width: 8, alignment: "Center" },
      { header: "40%", col: "F", width: 8, alignment: "Center" },
      { header: "50%", col: "G", width: 8, alignment: "Center" },
      { header: "60%", col: "H", width: 8, alignment: "Center" },
      { header: "70%", col: "I", width: 8, alignment: "Center" },
      { header: "80%", col: "J", width: 8, alignment: "Center" },
      { header: "90%", col: "K", width: 8, alignment: "Center" },
      { header: "100%", col: "L", width: 8, alignment: "Center" },
      { header: "Next action", col: "M", width: 54, alignment: "Left" },
    ],
    sampleData: [
      ["Drink 2L of water daily", "High", null, null, null, null, null, null, null, null, null, null, "Fill bottle each morning"],
      ["Read 3 books", "Medium", null, null, null, null, null, null, null, null, null, null, "Borrow next set of books"],
      ["Declutter bedroom", "Low", null, null, null, null, null, null, null, null, null, null, "Sort drawers next week"],
      ["Update portfolio", "High", null, null, null, null, null, null, null, null, null, null, "Update r\u00e9sum\u00e9"],
      ["Enrol in a week-long course on leadership", "High", null, null, null, null, null, null, null, null, null, null, "Watch module 2"],
      ["Apply to 10 job openings", "Medium", null, null, null, null, null, null, null, null, null, null, "Save 3 job listings"],
      ["Save $200 by end of week", "High", null, null, null, null, null, null, null, null, null, null, "Set up auto-transfer"],
      ["Track weekly spending", "Medium", null, null, null, null, null, null, null, null, null, null, "Group this week\u2019s expenses"],
      ["Open a digital bank", "Low", null, null, null, null, null, null, null, null, null, null, "Deposit $100"],
    ],
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "section_header", rows: 4 },
      { type: "accent", rows: 5 },
      { type: "column_header", rows: 6 },
      { type: "data", rows: [7, 9] },
      { type: "spacer", rows: 10 },
      { type: "section_header", rows: 11 },
      { type: "accent", rows: 12 },
      { type: "column_header", rows: 13 },
      { type: "data", rows: [14, 16] },
      { type: "spacer", rows: 17 },
      { type: "section_header", rows: 18 },
      { type: "accent", rows: 19 },
      { type: "column_header", rows: 20 },
      { type: "data", rows: [21, 23] },
      { type: "spacer", rows: 24 },
    ],
    columnSpan: "A:M",
    totalRows: 24,
  },
  sourceKind: "bundled",
};
