import type { TemplateDefinition } from "../types.js";

export const MONTHLY_TIME_SHEET: TemplateDefinition = {
  id: "monthly-time-sheet",
  name: "Monthly Time Sheet",
  category: "timesheet",
  description:
    "Track daily clock-in/out times, shift hours, and overtime across a full month with weekly subtotals.",
  design: {
    palette: {
      titleBg: "#052E34",
      titleFg: "#69CCCB",
      headerBg: "#052E34",
      headerFg: "#FFFFFF",
      labelBg: "#E78F5D",
      labelFg: "#000000",
      accentBg: "#FFFC7E",
      accentFg: "#000000",
      alternateBg: "",
      totalBg: "#052E34",
      totalFg: "#FFFFFF",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Aptos Narrow",
      titleSize: 56,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: false,
    titleBold: true,
    titleRowHeight: 72,
    defaultRowHeight: 20,
    headerRowHeight: 24,
  },
  structure: {
    title: "MONTHLY TIME SHEET",
    titleRow: 1,
    metaFields: [
      { label: "Period:", placeholder: "January 2026", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Employee:", placeholder: "Full Name", row: 2, labelCol: "D", valueCol: "E" },
      { label: "Supervisor:", placeholder: "Supervisor Name", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Shift:", placeholder: "Day", row: 3, labelCol: "D", valueCol: "E" },
    ],
    headerRow: 5,
    columns: [
      { header: "Date", col: "A", width: 14, alignment: "Center" },
      { header: "Clock In", col: "B", width: 12, alignment: "Center" },
      { header: "Clock Out", col: "C", width: 12, alignment: "Center" },
      { header: "Shift Hours", col: "D", width: 12, alignment: "Center" },
      { header: "Overtime", col: "E", width: 12, alignment: "Center" },
      { header: "Total Hours", col: "F", width: 12, alignment: "Center", isAccent: true },
    ],
    sampleData: [
      ["01/05/2026", "8:00 AM", "4:00 PM", 8, 0, 8],
      ["01/06/2026", "8:00 AM", "5:30 PM", 8, 1.5, 9.5],
      ["01/07/2026", "7:30 AM", "4:00 PM", 8, 0.5, 8.5],
      ["01/08/2026", "8:00 AM", "4:00 PM", 8, 0, 8],
    ],
    totalRow: {
      row: 34,
      label: "TOTAL",
      labelCol: "A",
      values: { D: 160, E: 12, F: 172 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "section_header", rows: 4 },
      { type: "column_header", rows: 5 },
      { type: "data", rows: [6, 12] },
      { type: "section_header", rows: 13 },
      { type: "column_header", rows: 14 },
      { type: "data", rows: [15, 21] },
      { type: "section_header", rows: 22 },
      { type: "column_header", rows: 23 },
      { type: "data", rows: [24, 30] },
      { type: "section_header", rows: 31 },
      { type: "column_header", rows: 32 },
      { type: "data", rows: [33, 33] },
      { type: "total", rows: 34 },
    ],
    columnSpan: "A:F",
    totalRows: 34,
  },
  sourceKind: "bundled",
};
