import type { TemplateDefinition } from "../types.js";

export const RESOURCE_PLANNING: TemplateDefinition = {
  id: "resource-planning",
  name: "Resource Planning",
  category: "planning",
  description:
    "Allocate team resources across projects with weekly hour assignments, capacity tracking, and utilization percentages.",
  design: {
    palette: {
      titleBg: "#283521",
      titleFg: "#EFFC5C",
      headerBg: "#283521",
      headerFg: "#EFFC5C",
      labelBg: "#EFFC5C",
      labelFg: "#283521",
      accentBg: "#1B6133",
      accentFg: "#EFFC5C",
      alternateBg: "",
      totalBg: "#283521",
      totalFg: "#EFFC5C",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Cambria",
      titleSize: 56,
      sectionHeaderSize: 13,
      headerSize: 13,
      bodySize: 13,
    },
    alternatingRows: false,
    titleBold: false,
    titleRowHeight: 98,
    defaultRowHeight: 30,
    headerRowHeight: 30,
  },
  structure: {
    title: "Resource Plan",
    titleRow: 1,
    metaFields: [
      { label: "Project Name:", placeholder: "Project Atlas", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Period:", placeholder: "Q2 2030", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Lead:", placeholder: "Zola Bekker", row: 4, labelCol: "A", valueCol: "B" },
    ],
    headerRow: 6,
    columns: [
      { header: "Name", col: "A", width: 19, alignment: "Left", isBold: true },
      { header: "Role", col: "B", width: 26, alignment: "Left" },
      { header: "Task", col: "C", width: 27, alignment: "Left" },
      { header: "Start", col: "D", width: 20, alignment: "Left" },
      { header: "End", col: "E", width: 17, alignment: "Left" },
      { header: "Week 1", col: "F", width: 12, alignment: "Center" },
      { header: "Week 2", col: "G", width: 12, alignment: "Center" },
      { header: "Week 3", col: "H", width: 12, alignment: "Center" },
      { header: "Week 4", col: "I", width: 12, alignment: "Center" },
      { header: "Total", col: "J", width: 15, alignment: "Center", isAccent: true },
      { header: "Capacity (Hours)", col: "K", width: 21, alignment: "Center" },
      { header: "Utilization %", col: "L", width: 19, alignment: "Center", isAccent: true },
      { header: "Status", col: "M", width: 13, alignment: "Left" },
      { header: "Notes", col: "N", width: 42, alignment: "Left" },
    ],
    sampleData: [
      ["Asher", "UI Designer", "Website redesign", "06/01/2030", "07/01/2030", 20, 25, 15, 10, 70, 160, "44%", "Balanced", "Front-end visuals"],
      ["Jesse", "Developer", "API integration", "06/01/2030", "07/01/2030", 35, 40, 38, 32, 145, 160, "91%", "Overloaded", "Needs support Week 2\u20133"],
      ["Isla", "QA Engineer", "Test suite", "06/01/2030", "07/01/2030", 15, 18, 20, 22, 75, 160, "47%", "Underutilized", "Can help dev team"],
      ["Lana", "Product Manager", "Project coordination", "06/01/2030", "07/01/2030", 25, 25, 25, 25, 100, 160, "63%", "Balanced", "Meetings + planning"],
      ["Rain", "Data Analyst", "Reporting", "06/01/2030", "07/01/2030", 10, 12, 15, 18, 55, 160, "34%", "Underutilized", "Assign to extra analysis"],
    ],
    totalRow: {
      row: 14,
      label: "TOTAL",
      labelCol: "E",
      values: { F: 105, G: 120, H: 113, I: 107, J: 445, K: 800 },
    },
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 4] },
      { type: "spacer", rows: 5 },
      { type: "column_header", rows: [6, 7] },
      { type: "data", rows: [8, 12] },
      { type: "spacer", rows: 13 },
      { type: "total", rows: 14 },
    ],
    columnSpan: "A:N",
    totalRows: 15,
  },
  sourceKind: "bundled",
};
