import type { TemplateDefinition } from "../types.js";

export const SALES_LEAD_TRACKING: TemplateDefinition = {
  id: "sales-lead-tracking",
  name: "Sales Lead Tracking",
  category: "sales",
  description:
    "Manage sales pipeline with lead status, follow-ups, and conversion tracking across contacts and companies.",
  design: {
    palette: {
      titleBg: "#C4DADD",
      titleFg: "#000000",
      headerBg: "#C3C68A",
      headerFg: "#000000",
      labelBg: "#C4DADD",
      labelFg: "#000000",
      accentBg: "#2F5496",
      accentFg: "#FFFFFF",
      alternateBg: "",
      totalBg: "#C3C68A",
      totalFg: "#000000",
    },
    typography: {
      fontFamily: "Arial Unicode MS",
      titleFontFamily: "Arial Unicode MS",
      titleSize: 53,
      sectionHeaderSize: 26,
      headerSize: 13,
      bodySize: 16,
    },
    alternatingRows: false,
    titleBold: false,
    titleRowHeight: 86,
    defaultRowHeight: 34,
    headerRowHeight: 30,
  },
  structure: {
    title: "Sales Lead Tracker",
    titleRow: 1,
    metaFields: [
      { label: "Sales Representative:", placeholder: "Irena Kim", row: 3, labelCol: "A", valueCol: "C" },
      { label: "Period of:", placeholder: "Q1 2035", row: 3, labelCol: "D", valueCol: "E" },
      { label: "Supervisor:", placeholder: "Boris Ercken", row: 4, labelCol: "A", valueCol: "C" },
      { label: "Last Updated:", placeholder: "03/01/2035", row: 4, labelCol: "D", valueCol: "E" },
    ],
    headerRow: 5,
    columns: [
      { header: "Lead Established", col: "A", width: 26, alignment: "Left" },
      { header: "Contact Name", col: "B", width: 34, alignment: "Left" },
      { header: "Position", col: "C", width: 29, alignment: "Left" },
      { header: "Company", col: "D", width: 28, alignment: "Left" },
      { header: "Contact Number", col: "E", width: 21, alignment: "Left" },
      { header: "Email", col: "F", width: 35, alignment: "Left" },
      { header: "Interest Level", col: "G", width: 22, alignment: "Left" },
      { header: "Next Step", col: "H", width: 22, alignment: "Left" },
    ],
    sampleData: [
      ["05/01/2035", "Eraya Sharma", "Purchasing Manager", "Creative Studio + Lab", "123-456-7890", "hello@reallygreatsite.com", "Medium", "Demo/Proposal"],
      ["05/03/2035", "Alaia Domingo", "Product Lead", "Visionary PR", "123-456-7891", "hello@reallygreatsite.com", "Medium", "Demo/Proposal"],
      ["05/03/2035", "Dominico Pascal", "Office Manager", "Nest Realty", "123-456-7892", "hello@reallygreatsite.com", "Low", "Inactive"],
      ["05/05/2035", "Leopold Ljungman", "Owner", "Escape Resort & Spa", "123-456-7893", "hello@reallygreatsite.com", "High", "Negotiation"],
      ["05/09/2035", "Jeremy Namgung", "Purchasing Manager", "Move Real Estate", "123-456-7894", "hello@reallygreatsite.com", "Medium", "Negotiation"],
      ["05/10/2035", "Caius Sanchez", "Product Lead", "Savvy Financial Services", "123-456-7895", "hello@reallygreatsite.com", "High", "Deal Closed"],
    ],
    zones: [
      { type: "title", rows: [1, 2] },
      { type: "meta", rows: [3, 4] },
      { type: "column_header", rows: 5 },
      { type: "data", rows: [6, 11] },
    ],
    columnSpan: "A:H",
    totalRows: 15,
  },
  sourceKind: "bundled",
};
