import type { TemplateDefinition } from "../types.js";

export const SALES_BALANCED_SCORECARD: TemplateDefinition = {
  id: "sales-balanced-scorecard",
  name: "Sales Balanced Scorecard",
  category: "sales",
  description:
    "Track sales performance across four perspectives: Financial, Customer, Internal Process, and Learning & Growth with objectives, metrics, targets, and actuals.",
  design: {
    palette: {
      titleBg: "#E8E7E3",
      titleFg: "#282627",
      headerBg: "#E8E7E3",
      headerFg: "#282627",
      labelBg: "#E8E7E3",
      labelFg: "#282627",
      accentBg: "#E8E7E3",
      accentFg: "#282627",
      alternateBg: "",
      totalBg: "#E8E7E3",
      totalFg: "#282627",
    },
    typography: {
      fontFamily: "Avenir Book",
      titleFontFamily: "Avenir Book",
      titleSize: 75,
      sectionHeaderSize: 14,
      headerSize: 11,
      bodySize: 11,
    },
    alternatingRows: false,
    titleBold: true,
    titleRowHeight: 90,
    defaultRowHeight: 20,
    headerRowHeight: 24,
  },
  structure: {
    title: "Sales Balanced Scorecard",
    titleRow: 1,
    metaFields: [
      { label: "Team:", placeholder: "Sales Division", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Period:", placeholder: "Q1 2026", row: 2, labelCol: "D", valueCol: "E" },
    ],
    headerRow: 4,
    columns: [
      { header: "Objective", col: "A", width: 22, alignment: "Left" },
      { header: "Metric", col: "B", width: 20, alignment: "Left" },
      { header: "Target", col: "C", width: 12, alignment: "Center" },
      { header: "Actual", col: "D", width: 12, alignment: "Center" },
      { header: "Status", col: "E", width: 12, alignment: "Center" },
      { header: "Notes", col: "F", width: 24, alignment: "Left" },
    ],
    sampleData: [
      ["Revenue Growth", "Quarterly Revenue", "$500K", "$475K", "On Track", ""],
      ["Cost Reduction", "Operating Costs", "-10%", "-8%", "At Risk", "Review vendor contracts"],
      ["Profit Margin", "Net Margin %", "25%", "23%", "On Track", ""],
      ["Customer Retention", "Retention Rate", "90%", "88%", "On Track", ""],
      ["New Customers", "New Accounts", "50", "42", "At Risk", "Increase outreach"],
      ["Satisfaction", "NPS Score", "70", "72", "Achieved", ""],
    ],
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: 2 },
      { type: "section_header", rows: 3 },
      { type: "column_header", rows: 4 },
      { type: "data", rows: [5, 7] },
      { type: "spacer", rows: 8 },
      { type: "section_header", rows: 9 },
      { type: "column_header", rows: 10 },
      { type: "data", rows: [11, 13] },
      { type: "spacer", rows: 14 },
      { type: "section_header", rows: 15 },
      { type: "column_header", rows: 16 },
      { type: "data", rows: [17, 19] },
      { type: "spacer", rows: 20 },
      { type: "section_header", rows: 21 },
      { type: "column_header", rows: 22 },
      { type: "data", rows: [23, 25] },
    ],
    columnSpan: "A:F",
    totalRows: 25,
  },
  sourceKind: "bundled",
};
