import type { TemplateDefinition } from "../types.js";

export const WORK_PLANNER: TemplateDefinition = {
  id: "work-planner",
  name: "Work Planner",
  category: "planning",
  description:
    "Organize daily tasks and meetings with time blocks, categories, priorities, and status tracking across a work week.",
  design: {
    palette: {
      titleBg: "#E1EF6D",
      titleFg: "#000000",
      headerBg: "#8D4552",
      headerFg: "#FFFFFF",
      labelBg: "#C3BAF4",
      labelFg: "#000000",
      accentBg: "#375623",
      accentFg: "#FFFFFF",
      alternateBg: "",
      totalBg: "#8D4552",
      totalFg: "#FFFFFF",
    },
    typography: {
      fontFamily: "Calibri",
      titleFontFamily: "Calibri",
      titleSize: 54,
      sectionHeaderSize: 14,
      headerSize: 14,
      bodySize: 11,
    },
    alternatingRows: false,
    titleBold: true,
    titleRowHeight: 66,
    defaultRowHeight: 20,
    headerRowHeight: 28,
  },
  structure: {
    title: "My Work Planner",
    titleRow: 1,
    metaFields: [
      { label: "Week of:", placeholder: "June 4", row: 2, labelCol: "A", valueCol: "B" },
      { label: "Company:", placeholder: "Vertex Systems", row: 2, labelCol: "D", valueCol: "E" },
      { label: "Name:", placeholder: "Inigo Bennett", row: 3, labelCol: "A", valueCol: "B" },
      { label: "Position:", placeholder: "Project Manager", row: 3, labelCol: "D", valueCol: "E" },
    ],
    headerRow: 4,
    columns: [
      { header: "Date", col: "A", width: 14, alignment: "Left" },
      { header: "Time", col: "B", width: 12, alignment: "Left" },
      { header: "Category", col: "C", width: 18, alignment: "Left" },
      { header: "Task", col: "D", width: 32, alignment: "Left" },
      { header: "Due Date", col: "E", width: 14, alignment: "Left" },
      { header: "Priority", col: "F", width: 14, alignment: "Left" },
      { header: "Status", col: "G", width: 18, alignment: "Left" },
      { header: "Notes", col: "H", width: 24, alignment: "Left" },
    ],
    sampleData: [
      ["Monday", "9:00 AM", "Comms", "Send weekly team update email", "06/04/2030", "Medium", "Not started", "Add dashboard link"],
      [null, "10:00 AM", "Meeting", "Project check-in with manager", "06/04/2030", "High", "Scheduled", "Bring updated timeline"],
      [null, "11:00 AM", "Focused Work", "Draft Q2 presentation slides", "06/10/2030", "High", "Scheduled", "Work on slides 1-10"],
      [null, "12:00 PM", "Break", "Lunch", null, null, null, null],
      [null, "1:00 PM", "Admin", "Update budget & expense tracker", "06/07/2030", "Medium", "In progress", "Waiting for receipts"],
      [null, "2:00 PM", "Focused Work", "Review client-provided files", "06/04/2030", "Medium", "In progress", null],
    ],
    zones: [
      { type: "title", rows: 1 },
      { type: "meta", rows: [2, 3] },
      { type: "column_header", rows: 4 },
      { type: "data", rows: [5, 13] },
      { type: "data", rows: [14, 22] },
    ],
    columnSpan: "A:H",
    totalRows: 22,
  },
  sourceKind: "bundled",
};
